package deploy

import (
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/sqoia-dev/clonr/pkg/api"
	"github.com/sqoia-dev/clonr/pkg/chroot"
	"github.com/sqoia-dev/clonr/pkg/ipmi"
)

// ifaceNameRe validates that a network interface name contains only safe
// characters before it is used to construct a filename.
var ifaceNameRe = regexp.MustCompile(`^[a-zA-Z0-9._:-]+$`)

// mdRaidArraysRules is the content of the 63-md-raid-arrays.rules udev rule
// file. It is embedded directly so it can be injected into the deployed OS
// chroot even when the deploy host (PXE initramfs) does not have it installed.
// This rule causes udev to create /dev/disk/by-id/md-uuid-* and
// /dev/disk/by-id/md-name-* symlinks when md arrays become active, which
// dracut's initqueue finished-hooks depend on to declare the root device ready.
const mdRaidArraysRules = `# do not edit this file, it will be overwritten on update

SUBSYSTEM!="block", GOTO="md_end"

# handle md arrays
ACTION=="remove", GOTO="md_end"
KERNEL!="md*", GOTO="md_end"

# partitions have no md/{array_state,metadata_version}, but should not
# for that reason be ignored.
ENV{DEVTYPE}=="partition", GOTO="md_ignore_state"

# container devices have a metadata version of e.g. 'external:ddf' and
# never leave state 'inactive'
ATTR{md/metadata_version}=="external:[A-Za-z]*", ATTR{md/array_state}=="inactive", GOTO="md_ignore_state"
TEST!="md/array_state", ENV{SYSTEMD_READY}="0", GOTO="md_end"
ATTR{md/array_state}=="clear*|inactive", ENV{SYSTEMD_READY}="0", GOTO="md_end"
ATTR{md/sync_action}=="reshape", ENV{RESHAPE_ACTIVE}="yes"
LABEL="md_ignore_state"

IMPORT{program}="/usr/sbin/mdadm --detail --no-devices --export $devnode"
ENV{DEVTYPE}=="disk", ENV{MD_NAME}=="?*", SYMLINK+="disk/by-id/md-name-$env{MD_NAME}", OPTIONS+="string_escape=replace"
ENV{DEVTYPE}=="disk", ENV{MD_UUID}=="?*", SYMLINK+="disk/by-id/md-uuid-$env{MD_UUID}"
ENV{DEVTYPE}=="disk", ENV{MD_DEVNAME}=="?*", SYMLINK+="md/$env{MD_DEVNAME}"
ENV{DEVTYPE}=="partition", ENV{MD_NAME}=="?*", SYMLINK+="disk/by-id/md-name-$env{MD_NAME}-part%n", OPTIONS+="string_escape=replace"
ENV{DEVTYPE}=="partition", ENV{MD_UUID}=="?*", SYMLINK+="disk/by-id/md-uuid-$env{MD_UUID}-part%n"
ENV{DEVTYPE}=="partition", ENV{MD_DEVNAME}=="*[^0-9]", SYMLINK+="md/$env{MD_DEVNAME}%n"
ENV{DEVTYPE}=="partition", ENV{MD_DEVNAME}=="*[0-9]", SYMLINK+="md/$env{MD_DEVNAME}p%n"

IMPORT{builtin}="blkid"
OPTIONS+="link_priority=100"
OPTIONS+="watch"
ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{ID_FS_UUID_ENC}=="?*", SYMLINK+="disk/by-uuid/$env{ID_FS_UUID_ENC}"
ENV{ID_FS_USAGE}=="filesystem|other", ENV{ID_PART_ENTRY_UUID}=="?*", SYMLINK+="disk/by-partuuid/$env{ID_PART_ENTRY_UUID}"
ENV{ID_FS_USAGE}=="filesystem|other", ENV{ID_FS_LABEL_ENC}=="?*", SYMLINK+="disk/by-label/$env{ID_FS_LABEL_ENC}"

ENV{MD_LEVEL}=="raid[1-9]*", ENV{SYSTEMD_WANTS}+="mdmonitor.service"

# Tell systemd to run mdmon for our container, if we need it.
ENV{MD_LEVEL}=="raid[1-9]*", ENV{MD_CONTAINER}=="?*", PROGRAM="/usr/bin/readlink $env{MD_CONTAINER}", ENV{MD_MON_THIS}="%c"
ENV{MD_MON_THIS}=="?*", TEST=="/etc/initrd-release", PROGRAM="/usr/bin/basename $env{MD_MON_THIS}", ENV{SYSTEMD_WANTS}+="mdmon@initrd-%c.service"
ENV{MD_MON_THIS}=="?*", TEST!="/etc/initrd-release", PROGRAM="/usr/bin/basename $env{MD_MON_THIS}", ENV{SYSTEMD_WANTS}+="mdmon@%c.service"
ENV{RESHAPE_ACTIVE}=="yes", PROGRAM="/usr/bin/basename $env{MD_MON_THIS}", ENV{SYSTEMD_WANTS}+="mdadm-grow-continue@%c.service"

LABEL="md_end"
`

// mdRaidAssemblyRules is the content of the 64-md-raid-assembly.rules udev
// rule file. It handles incremental RAID assembly (adding member devices one
// by one as they appear). Embedded directly for the same reason as
// mdRaidArraysRules above.
const mdRaidAssemblyRules = `# do not edit this file, it will be overwritten on update

# Don't process any events if anaconda is running as anaconda brings up
# raid devices manually
ENV{ANACONDA}=="?*", GOTO="md_inc_end"
# assemble md arrays

SUBSYSTEM!="block", GOTO="md_inc_end"

# skip non-initialized devices
ENV{SYSTEMD_READY}=="0", GOTO="md_inc_end"

# handle potential components of arrays (the ones supported by md)
# For member devices which are md/dm devices, we don't need to
# handle add event. Because md/dm devices need to do some init jobs.
# Then the change event happens.
# When adding md/dm devices, ID_FS_TYPE can only be linux_raid_member
# after change event happens.
ENV{ID_FS_TYPE}=="linux_raid_member", GOTO="md_inc"

# "noiswmd" on kernel command line stops mdadm from handling
#  "isw" (aka IMSM - Intel RAID).
# "nodmraid" on kernel command line stops mdadm from handling
#  "isw" or "ddf".
IMPORT{cmdline}="noiswmd"
IMPORT{cmdline}="nodmraid"

ENV{nodmraid}=="?*", GOTO="md_inc_end"
ENV{ID_FS_TYPE}=="ddf_raid_member", GOTO="md_inc"
ENV{noiswmd}=="?*", GOTO="md_inc_end"
ENV{ID_FS_TYPE}=="isw_raid_member", ACTION!="change", GOTO="md_inc"
GOTO="md_inc_end"

LABEL="md_inc"

# Bare disks are ready when add event happens, the raid can be assembled.
ACTION=="change", KERNEL!="dm-*|md*", GOTO="md_inc_end"

# remember you can limit what gets auto/incrementally assembled by
# mdadm.conf(5)'s 'AUTO' and selectively whitelist using 'ARRAY'
ACTION!="remove", IMPORT{program}="/usr/sbin/mdadm --incremental --export $devnode --offroot $env{DEVLINKS}"
ACTION!="remove", ENV{MD_STARTED}=="*unsafe*", ENV{MD_FOREIGN}=="no", ENV{SYSTEMD_WANTS}+="mdadm-last-resort@$env{MD_DEVICE}.timer"

ACTION=="remove", ENV{ID_PATH}=="?*", RUN+="/usr/sbin/mdadm -If $devnode --path $env{ID_PATH}"
ACTION=="remove", ENV{ID_PATH}!="?*", RUN+="/usr/sbin/mdadm -If $devnode"

LABEL="md_inc_end"
`

// applyNodeConfig writes all node-specific identity into the deployed filesystem
// rooted at mountRoot. This function is called by both FilesystemDeployer and
// BlockDeployer after the image is on disk.
//
// Order of operations:
//  1. Hostname
//  2. Network config (NetworkManager keyfiles)
//  3. SSH authorized_keys for root
//  4. /etc/fstab UUID update
//  5. Kernel args (GRUB)
//  6. BMC / IPMI network and credentials (if cfg.BMC is set)
//  7. InfiniBand / IPoIB config (if cfg.IBConfig is set)
func applyNodeConfig(ctx context.Context, cfg api.NodeConfig, mountRoot string) error {
	log := logger()

	log.Info().Str("hostname", cfg.Hostname).Msg("finalize: writing /etc/hostname")
	if err := writeHostname(mountRoot, cfg.Hostname, cfg.FQDN); err != nil {
		return fmt.Errorf("finalize: hostname: %w", err)
	}
	log.Info().Str("hostname", cfg.Hostname).Msg("finalize: wrote /etc/hostname")

	log.Info().Int("interfaces", len(cfg.Interfaces)).Msg("finalize: writing NetworkManager connection profiles")
	if err := writeNetworkConfig(mountRoot, cfg.Interfaces); err != nil {
		return fmt.Errorf("finalize: network: %w", err)
	}
	for _, iface := range cfg.Interfaces {
		log.Info().Str("interface", iface.Name).Str("ip", iface.IPAddress).
			Msgf("finalize: wrote /etc/NetworkManager/system-connections/%s.nmconnection", iface.Name)
	}

	if len(cfg.SSHKeys) > 0 {
		log.Info().Int("keys", len(cfg.SSHKeys)).Msg("finalize: writing /root/.ssh/authorized_keys")
		if err := writeSSHKeys(mountRoot, cfg.SSHKeys); err != nil {
			return fmt.Errorf("finalize: ssh keys: %w", err)
		}
		log.Info().Int("keys", len(cfg.SSHKeys)).Msg("finalize: wrote /root/.ssh/authorized_keys")
	}

	if cfg.KernelArgs != "" {
		log.Info().Str("args", cfg.KernelArgs).Msg("finalize: applying kernel args to /etc/default/grub")
		if err := applyKernelArgs(ctx, mountRoot, cfg.KernelArgs); err != nil {
			// Non-fatal: the GRUB config file edit may have succeeded even if
			// grub2-mkconfig failed in the chroot. Log prominently so operators
			// know to verify the bootloader configuration manually.
			log.Warn().Err(err).Msg("WARNING: finalize: kernel args update failed (non-fatal) — manual intervention may be required")
		} else {
			log.Info().Str("args", cfg.KernelArgs).Msg("finalize: kernel args applied, ran grub2-mkconfig")
		}
	}

	// BMC / IPMI — configure local BMC network and credentials.
	// This operates on the physical BMC directly (not the chroot), so it is
	// done here rather than inside the deployed filesystem.
	if cfg.BMC != nil {
		log.Info().Str("bmc_ip", cfg.BMC.IPAddress).Msg("finalize: configuring BMC via ipmitool")
		if err := applyBMCConfig(ctx, cfg.BMC); err != nil {
			// Non-fatal: BMC configuration failure should not abort a deployment.
			// The operator can manually configure the BMC afterward.
			log.Warn().Err(err).Msg("WARNING: finalize: BMC configuration failed (non-fatal)")
		} else {
			log.Info().Str("bmc_ip", cfg.BMC.IPAddress).Msg("finalize: BMC configured")
		}
	}

	// InfiniBand / IPoIB — write udev rules and NetworkManager profiles into
	// the deployed filesystem so IB interfaces come up correctly on first boot.
	if len(cfg.IBConfig) > 0 {
		log.Info().Int("devices", len(cfg.IBConfig)).Msg("finalize: writing InfiniBand/IPoIB configuration")
		if err := writeIBConfig(mountRoot, cfg.IBConfig); err != nil {
			return fmt.Errorf("finalize: ib config: %w", err)
		}
		log.Info().Int("devices", len(cfg.IBConfig)).Msg("finalize: InfiniBand/IPoIB configuration written")
	}

	return nil
}

// applyBMCConfig configures the local BMC via ipmitool.
// This targets the physical BMC of the node being finalized, not the chroot.
func applyBMCConfig(ctx context.Context, bmc *api.BMCNodeConfig) error {
	c := &ipmi.Client{} // local BMC — no host flags

	bmcCfg := ipmi.BMCConfig{
		Channel:   1,
		IPAddress: bmc.IPAddress,
		Netmask:   bmc.Netmask,
		Gateway:   bmc.Gateway,
		IPSource:  "static",
	}
	if err := c.SetBMCNetwork(ctx, bmcCfg); err != nil {
		return fmt.Errorf("set bmc network: %w", err)
	}

	if bmc.Username != "" && bmc.Password != "" {
		// Use user slot 2 — slot 1 is typically the reserved anonymous user.
		if err := c.SetBMCUser(ctx, 2, bmc.Username, bmc.Password); err != nil {
			return fmt.Errorf("set bmc user: %w", err)
		}
	}
	return nil
}

// writeIBConfig writes IPoIB NetworkManager connection profiles and udev rules
// for each InfiniBand device into the deployed filesystem at mountRoot.
func writeIBConfig(mountRoot string, ibCfgs []api.IBInterfaceConfig) error {
	nmDir := filepath.Join(mountRoot, "etc", "NetworkManager", "system-connections")
	if err := os.MkdirAll(nmDir, 0o700); err != nil {
		return fmt.Errorf("mkdir NM connections: %w", err)
	}

	for _, ib := range ibCfgs {
		if err := writeIPoIBProfile(nmDir, ib); err != nil {
			return fmt.Errorf("ib device %s: %w", ib.DeviceName, err)
		}
	}
	return nil
}

// writeIPoIBProfile writes a NetworkManager keyfile for an IPoIB interface.
// The interface name is derived from the IB device name (e.g. mlx5_0 → ib0).
func writeIPoIBProfile(nmDir string, ib api.IBInterfaceConfig) error {
	// IPoIB interface naming: mlx5_0→ib0, mlx5_1→ib1, hfi1_0→ib0, etc.
	// We use the device name directly as the NM connection id and interface-name.
	ifaceName := ibDeviceToIPoIBName(ib.DeviceName)

	// Validate the derived interface name before using it as a filename component.
	if !ifaceNameRe.MatchString(ifaceName) {
		return fmt.Errorf("derived IB interface name %q contains invalid characters", ifaceName)
	}

	mtu := ib.MTU
	if mtu == 0 {
		if strings.EqualFold(ib.IPoIBMode, "connected") {
			mtu = 65520
		} else {
			mtu = 2044 // datagram mode default
		}
	}

	mode := strings.ToLower(ib.IPoIBMode)
	if mode == "" {
		mode = "datagram"
	}

	var sb strings.Builder
	sb.WriteString("[connection]\n")
	fmt.Fprintf(&sb, "id=%s\n", ifaceName)
	sb.WriteString("type=infiniband\n")
	fmt.Fprintf(&sb, "interface-name=%s\n", ifaceName)
	sb.WriteString("\n")

	sb.WriteString("[infiniband]\n")
	fmt.Fprintf(&sb, "transport-mode=%s\n", mode)
	fmt.Fprintf(&sb, "mtu=%d\n", mtu)
	if len(ib.PKeys) > 0 {
		// Write the first partition key; additional pkeys require separate profiles.
		fmt.Fprintf(&sb, "p-key=%s\n", ib.PKeys[0])
	}
	sb.WriteString("\n")

	sb.WriteString("[ipv4]\n")
	if ib.IPAddress != "" {
		ip, prefix := parseIPCIDR(ib.IPAddress)
		sb.WriteString("method=manual\n")
		fmt.Fprintf(&sb, "address1=%s/%s\n", ip, prefix)
	} else {
		sb.WriteString("method=disabled\n")
	}
	sb.WriteString("\n")

	sb.WriteString("[ipv6]\n")
	sb.WriteString("method=ignore\n")

	filename := filepath.Join(nmDir, ifaceName+".nmconnection")
	return os.WriteFile(filename, []byte(sb.String()), 0o600)
}

// ibDeviceToIPoIBName maps an IB device name to its IPoIB interface name.
// e.g. "mlx5_0" → "ib0", "mlx5_1" → "ib1", "hfi1_0" → "ib0"
func ibDeviceToIPoIBName(devName string) string {
	// Extract trailing digit after the last underscore for the IB port index.
	idx := strings.LastIndex(devName, "_")
	if idx >= 0 && idx < len(devName)-1 {
		suffix := devName[idx+1:]
		// Only use the numeric suffix as the ib interface index.
		allDigits := true
		for _, c := range suffix {
			if c < '0' || c > '9' {
				allDigits = false
				break
			}
		}
		if allDigits {
			return "ib" + suffix
		}
	}
	return "ib0"
}

// writeHostname writes /etc/hostname and updates /etc/hosts.
func writeHostname(mountRoot, hostname, fqdn string) error {
	if hostname == "" {
		return nil
	}

	hostnameFile := filepath.Join(mountRoot, "etc", "hostname")
	if err := os.MkdirAll(filepath.Dir(hostnameFile), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(hostnameFile, []byte(hostname+"\n"), 0o644); err != nil {
		return fmt.Errorf("write /etc/hostname: %w", err)
	}

	// Update /etc/hosts: add or replace the 127.0.1.1 line.
	hostsFile := filepath.Join(mountRoot, "etc", "hosts")
	existing, err := os.ReadFile(hostsFile)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read /etc/hosts: %w", err)
	}

	// Build the new hosts content.
	var lines []string
	for _, line := range strings.Split(string(existing), "\n") {
		// Remove any existing 127.0.1.1 lines.
		if strings.HasPrefix(strings.TrimSpace(line), "127.0.1.1") {
			continue
		}
		lines = append(lines, line)
	}

	entry := "127.0.1.1\t" + hostname
	if fqdn != "" && fqdn != hostname {
		entry = "127.0.1.1\t" + fqdn + "\t" + hostname
	}
	lines = append(lines, entry)

	content := strings.Join(lines, "\n")
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return os.WriteFile(hostsFile, []byte(content), 0o644)
}

// writeNetworkConfig writes NetworkManager keyfile connections for each interface.
// This is the standard config format on Rocky Linux 8/9/10, RHEL 8/9/10, and derivatives.
//
// When interfaces is empty a single fallback "wired-dhcp" connection is written
// that matches any wired interface (no interface-name restriction) and requests a
// DHCP lease. This ensures the node is reachable after first boot even when the
// caller does not specify explicit interface config. Without this, Rocky Linux 10
// will not configure any NIC by default because NM's no-auto-default behavior
// is distribution-controlled and may not activate wired devices automatically.
func writeNetworkConfig(mountRoot string, interfaces []api.InterfaceConfig) error {
	nmDir := filepath.Join(mountRoot, "etc", "NetworkManager", "system-connections")
	if err := os.MkdirAll(nmDir, 0o700); err != nil {
		return fmt.Errorf("mkdir NM connections: %w", err)
	}

	if len(interfaces) == 0 {
		// Write a wildcard DHCP profile so the first wired interface comes up.
		fallback := `[connection]
id=wired-dhcp
type=ethernet
autoconnect=true
autoconnect-priority=-100

[ethernet]

[ipv4]
method=auto

[ipv6]
method=ignore
`
		path := filepath.Join(nmDir, "wired-dhcp.nmconnection")
		return os.WriteFile(path, []byte(fallback), 0o600)
	}

	for _, iface := range interfaces {
		if err := writeNMKeyfile(nmDir, iface); err != nil {
			return fmt.Errorf("interface %s: %w", iface.Name, err)
		}
	}
	return nil
}

// writeNMKeyfile writes a single NetworkManager keyfile for an interface.
func writeNMKeyfile(nmDir string, iface api.InterfaceConfig) error {
	name := iface.Name
	if name == "" {
		name = iface.MACAddress
	}

	// Validate the interface name before using it as a filename component.
	if !ifaceNameRe.MatchString(name) {
		return fmt.Errorf("interface name %q contains invalid characters (must match ^[a-zA-Z0-9._:-]+$)", name)
	}

	// Parse IP and prefix from CIDR.
	ip, prefix := parseIPCIDR(iface.IPAddress)

	var sb strings.Builder
	sb.WriteString("[connection]\n")
	fmt.Fprintf(&sb, "id=%s\n", name)
	fmt.Fprintf(&sb, "type=ethernet\n")
	fmt.Fprintf(&sb, "interface-name=%s\n", name)
	sb.WriteString("\n")

	sb.WriteString("[ethernet]\n")
	if iface.MACAddress != "" {
		fmt.Fprintf(&sb, "mac-address=%s\n", iface.MACAddress)
	}
	if iface.MTU > 0 {
		fmt.Fprintf(&sb, "mtu=%d\n", iface.MTU)
	}
	sb.WriteString("\n")

	sb.WriteString("[ipv4]\n")
	if ip != "" {
		sb.WriteString("method=manual\n")
		fmt.Fprintf(&sb, "address1=%s/%s", ip, prefix)
		if iface.Gateway != "" {
			fmt.Fprintf(&sb, ",%s", iface.Gateway)
		}
		sb.WriteString("\n")
		if len(iface.DNS) > 0 {
			fmt.Fprintf(&sb, "dns=%s;\n", strings.Join(iface.DNS, ";"))
		}
	} else {
		sb.WriteString("method=auto\n")
	}
	sb.WriteString("\n")

	sb.WriteString("[ipv6]\n")
	sb.WriteString("method=ignore\n")

	filename := filepath.Join(nmDir, name+".nmconnection")
	// Mode 0600 is required by NM — it refuses to load world-readable keyfiles.
	return os.WriteFile(filename, []byte(sb.String()), 0o600)
}

// parseIPCIDR splits "192.168.1.10/24" into ("192.168.1.10", "24").
// Returns ("", "") if the input is empty or malformed.
func parseIPCIDR(cidr string) (ip, prefix string) {
	parts := strings.SplitN(cidr, "/", 2)
	if len(parts) == 2 {
		return parts[0], parts[1]
	}
	if len(parts) == 1 && parts[0] != "" {
		return parts[0], "24" // default /24 if no prefix given
	}
	return "", ""
}

// writeSSHKeys writes authorized_keys for root.
func writeSSHKeys(mountRoot string, keys []string) error {
	sshDir := filepath.Join(mountRoot, "root", ".ssh")
	if err := os.MkdirAll(sshDir, 0o700); err != nil {
		return fmt.Errorf("mkdir .ssh: %w", err)
	}

	authKeysPath := filepath.Join(sshDir, "authorized_keys")
	content := strings.Join(keys, "\n")
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}

	return os.WriteFile(authKeysPath, []byte(content), 0o600)
}

// applyKernelArgs appends extra kernel args to the GRUB default config.
// It looks for GRUB_CMDLINE_LINUX in /etc/default/grub and appends args.
func applyKernelArgs(ctx context.Context, mountRoot, kernelArgs string) error {
	grubDefault := filepath.Join(mountRoot, "etc", "default", "grub")
	raw, err := os.ReadFile(grubDefault)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // no GRUB config — might be a systemd-boot system
		}
		return fmt.Errorf("read grub config: %w", err)
	}

	content := string(raw)
	updated := false
	var newLines []string
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "GRUB_CMDLINE_LINUX=") {
			// Strip trailing quote, append args, re-add quote.
			trimmed := strings.TrimSuffix(strings.TrimSpace(line), `"`)
			line = trimmed + " " + kernelArgs + `"`
			updated = true
		}
		newLines = append(newLines, line)
	}

	if !updated {
		// Key not present — append it.
		newLines = append(newLines, fmt.Sprintf(`GRUB_CMDLINE_LINUX="%s"`, kernelArgs))
	}

	newContent := strings.Join(newLines, "\n")
	if err := os.WriteFile(grubDefault, []byte(newContent), 0o644); err != nil {
		return fmt.Errorf("write grub config: %w", err)
	}

	// Attempt to regenerate grub.cfg inside the chroot using chroot + grub2-mkconfig.
	// grub2-mkconfig may not be available in all chroot environments (e.g. minimal
	// initramfs deployments or systemd-boot systems). The /etc/default/grub edit
	// above is the durable change; grub2-mkconfig makes it take effect immediately.
	// Failure here is non-fatal but MUST be surfaced — the node may not boot with
	// the requested kernel arguments without manual intervention.
	grubCfgPath := findGrubCfg(mountRoot)
	if grubCfgPath != "" {
		logger().Info().Str("grub_cfg", grubCfgPath).Msg("running grub2-mkconfig in chroot")
		chrootArgs := []string{mountRoot, "grub2-mkconfig", "-o", grubCfgPath}
		if err := runAndLog(ctx, "grub2-mkconfig", exec.CommandContext(ctx, "chroot", chrootArgs...)); err != nil {
			return fmt.Errorf(
				"WARNING: grub configuration update failed — node may not boot with the requested "+
					"kernel arguments. Manual intervention may be required. "+
					"grub2-mkconfig: %w",
				err,
			)
		}
		logger().Info().Str("grub_cfg", grubCfgPath).Msg("grub2-mkconfig complete")
	}

	return nil
}

// findGrubCfg looks for grub.cfg in common locations within the mount root.
func findGrubCfg(mountRoot string) string {
	candidates := []string{
		"/boot/grub2/grub.cfg",
		"/boot/grub/grub.cfg",
		"/boot/efi/EFI/rocky/grub.cfg",
		"/boot/efi/EFI/redhat/grub.cfg",
		"/boot/efi/EFI/centos/grub.cfg",
	}
	for _, c := range candidates {
		if _, err := os.Stat(filepath.Join(mountRoot, c)); err == nil {
			return c // return path relative to chroot root
		}
	}
	return ""
}

// installKernelInChroot installs the kernel and GRUB2 bootloader packages inside
// the deployed chroot using dnf. This is needed when the image was captured
// without /boot contents (e.g. --one-file-system capture with a separate /boot
// partition on the source). After this function returns, /boot/grub2/grub.cfg
// and at least one vmlinuz + initramfs pair will exist in the chroot.
//
// The function mounts /proc, /sys, and /dev into the chroot before running dnf
// because dnf's scriptlets require these virtual filesystems.
func installKernelInChroot(ctx context.Context, mountRoot, targetDisk string) error {
	log := logger()

	// Bind-mount virtual filesystems required by dnf/rpm scriptlets.
	type bindMount struct{ src, dst string }
	binds := []bindMount{
		{"/proc", filepath.Join(mountRoot, "proc")},
		{"/sys", filepath.Join(mountRoot, "sys")},
		{"/dev", filepath.Join(mountRoot, "dev")},
		{"/dev/pts", filepath.Join(mountRoot, "dev", "pts")},
	}
	for _, b := range binds {
		if err := os.MkdirAll(b.dst, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", b.dst, err)
		}
		if out, err := exec.CommandContext(ctx, "mount", "--bind", b.src, b.dst).CombinedOutput(); err != nil {
			return fmt.Errorf("bind-mount %s → %s: %w\n%s", b.src, b.dst, err, string(out))
		}
	}
	defer func() {
		// Unmount in reverse order.
		for i := len(binds) - 1; i >= 0; i-- {
			_ = exec.Command("umount", "-l", binds[i].dst).Run()
		}
	}()

	// Copy the host's /etc/resolv.conf into the chroot so dnf can reach the network.
	resolvSrc := "/etc/resolv.conf"
	resolvDst := filepath.Join(mountRoot, "etc", "resolv.conf")
	if data, err := os.ReadFile(resolvSrc); err == nil {
		_ = os.WriteFile(resolvDst, data, 0o644)
	}

	// Ensure /tmp exists and is writable inside the chroot.
	// dnf requires /tmp for its download cache and RPM scriptlets.
	// Images captured without /tmp (or with sticky-bit /tmp permissions stripped)
	// will cause dnf to fail with "mkstemp: No such file or directory".
	tmpDir := filepath.Join(mountRoot, "tmp")
	if err := os.MkdirAll(tmpDir, 0o1777); err != nil {
		log.Warn().Err(err).Str("path", tmpDir).Msg("finalize/boot: could not create /tmp in chroot (non-fatal)")
	}
	// Ensure /boot/grub2 directory exists so grub2-mkconfig can write grub.cfg.
	grub2Dir := filepath.Join(mountRoot, "boot", "grub2")
	if err := os.MkdirAll(grub2Dir, 0o755); err != nil {
		log.Warn().Err(err).Str("path", grub2Dir).Msg("finalize/boot: could not create /boot/grub2 in chroot (non-fatal)")
	}

	// Install kernel and grub2-pc inside the deployed chroot.
	// We always use "chroot <mountRoot> dnf" because the initramfs (deployment host)
	// does not have dnf — it must be invoked from within the deployed image, which
	// is a full Rocky Linux 9 system with /usr/bin/dnf present.
	//
	// IMPORTANT: disable all third-party repos (epel, epel-next, etc.) during
	// this install. The initramfs environment has no external DNS resolution and
	// any attempt to reach mirrors.fedoraproject.org or similar will time out and
	// cause dnf to fail. Kernel and grub2 are in the base Rocky repos (baseos,
	// appstream, extras) which are served by the local mirrorlist / fastest-mirror
	// cache inside the chroot, but to be safe we explicitly enable only baseos and
	// appstream and disable everything else.
	packages := []string{"kernel", "grub2-pc", "grub2-tools"}
	log.Info().Strs("packages", packages).Msg("finalize/boot: installing kernel + grub2 via chroot dnf (baseos+appstream only)")
	chrootDnfArgs := append([]string{
		mountRoot, "dnf", "-y",
		"--setopt=install_weak_deps=False",
		"--disablerepo=*",
		"--enablerepo=baseos",
		"--enablerepo=appstream",
		"install",
	}, packages...)
	if err := runAndLog(ctx, "chroot-dnf-kernel-install", exec.CommandContext(ctx, "chroot", chrootDnfArgs...)); err != nil {
		return fmt.Errorf("chroot dnf install kernel+grub2: %w", err)
	}

	// Install GRUB to the target disk MBR now that the grub2-pc package is present.
	// grub2-install needs access to /boot (already mounted) and /dev.
	bootDir := filepath.Join(mountRoot, "boot")
	grubInstallArgs := []string{"--target=i386-pc", "--boot-directory=" + bootDir, "--recheck", targetDisk}
	log.Info().Str("disk", targetDisk).Msg("finalize/boot: re-running grub2-install after kernel install")
	if err := runAndLog(ctx, "grub2-install", exec.CommandContext(ctx, "grub2-install", grubInstallArgs...)); err != nil {
		log.Warn().Err(err).Msg("finalize/boot: grub2-install after kernel install failed (non-fatal)")
	}

	// Generate grub.cfg inside the chroot.
	grubCfgInChroot := "/boot/grub2/grub.cfg"
	log.Info().Str("grub_cfg", grubCfgInChroot).Msg("finalize/boot: generating grub.cfg via chroot grub2-mkconfig")
	mkcfgCmd := exec.CommandContext(ctx, "chroot", mountRoot, "grub2-mkconfig", "-o", grubCfgInChroot)
	if err := runAndLog(ctx, "grub2-mkconfig", mkcfgCmd); err != nil {
		return fmt.Errorf("finalize/boot: grub2-mkconfig after kernel install: %w", err)
	}
	log.Info().Msg("finalize/boot: kernel + grub2 installed and configured")
	return nil
}

// installEFIBootloaderInChroot installs grub2-efi-x64 and shim-x64 inside the
// deployed chroot via dnf. This is required for UEFI images built from ISO where
// the tar archive only contains empty /boot/efi/EFI/rocky/ stub directories —
// the actual EFI binaries (grubx64.efi, shimx64.efi) live on the ESP partition
// of the source system and are never included in the rootfs capture.
//
// After this function returns, /boot/efi/EFI/rocky/grubx64.efi will be present
// on the mounted ESP so that FixEFIBoot's NVRAM entry can point to a real binary.
func installEFIBootloaderInChroot(ctx context.Context, mountRoot string) error {
	log := logger()

	// Bind-mount virtual filesystems required by dnf/rpm scriptlets.
	type bindMount struct{ src, dst string }
	binds := []bindMount{
		{"/proc", filepath.Join(mountRoot, "proc")},
		{"/sys", filepath.Join(mountRoot, "sys")},
		{"/dev", filepath.Join(mountRoot, "dev")},
		{"/dev/pts", filepath.Join(mountRoot, "dev", "pts")},
	}
	for _, b := range binds {
		if err := os.MkdirAll(b.dst, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", b.dst, err)
		}
		if out, err := exec.CommandContext(ctx, "mount", "--bind", b.src, b.dst).CombinedOutput(); err != nil {
			return fmt.Errorf("bind-mount %s → %s: %w\n%s", b.src, b.dst, err, string(out))
		}
	}
	defer func() {
		for i := len(binds) - 1; i >= 0; i-- {
			_ = exec.Command("umount", "-l", binds[i].dst).Run()
		}
	}()

	// Copy /etc/resolv.conf so dnf can reach package mirrors.
	resolvDst := filepath.Join(mountRoot, "etc", "resolv.conf")
	if data, err := os.ReadFile("/etc/resolv.conf"); err == nil {
		_ = os.WriteFile(resolvDst, data, 0o644)
	}

	// Ensure /tmp is writable — required by dnf for its download cache.
	if err := os.MkdirAll(filepath.Join(mountRoot, "tmp"), 0o1777); err != nil {
		log.Warn().Err(err).Msg("finalize/boot: could not create /tmp in chroot (non-fatal)")
	}

	// Ensure the ESP mount point directory exists.
	espDir := filepath.Join(mountRoot, "boot", "efi")
	if err := os.MkdirAll(espDir, 0o700); err != nil {
		log.Warn().Err(err).Str("path", espDir).Msg("finalize/boot: could not create /boot/efi in chroot (non-fatal)")
	}

	// Install grub2-efi-x64 and shim-x64. Their %post scriptlets run grub2-install
	// or copy the EFI binary to /boot/efi/EFI/rocky/grubx64.efi. We also install
	// grub2-efi-x64-modules so grub2-mkconfig can reference them.
	// Only baseos and appstream are enabled — no external mirrors needed.
	packages := []string{"grub2-efi-x64", "shim-x64", "grub2-efi-x64-modules"}
	log.Info().Strs("packages", packages).Msg("finalize/boot: installing EFI bootloader packages via chroot dnf")
	chrootDnfArgs := append([]string{
		mountRoot, "dnf", "-y",
		"--setopt=install_weak_deps=False",
		"--disablerepo=*",
		"--enablerepo=baseos",
		"--enablerepo=appstream",
		"install",
	}, packages...)
	if err := runAndLog(ctx, "chroot-dnf-efi-install", exec.CommandContext(ctx, "chroot", chrootDnfArgs...)); err != nil {
		return fmt.Errorf("chroot dnf install grub2-efi-x64 shim-x64: %w", err)
	}
	log.Info().Msg("finalize/boot: EFI bootloader packages installed")
	return nil
}

// applyBootConfig performs the post-install steps required to produce a bootable
// deployed filesystem. It must be called after grub2-install has written the
// bootloader to the MBR/bios-boot partition and after the full tar extraction is
// complete. The steps are:
//
//  1. Regenerate /boot/grub2/grub.cfg via grub2-mkconfig inside a chroot with
//     /proc, /sys, and /dev bind-mounted (required by grub2-mkconfig).
//  2. Regenerate the initramfs via dracut --no-hostonly so the resulting image
//     contains drivers for all hardware, not just the capture source's hardware
//     (critical for virtio_blk/virtio_net on VMs).
//  3. Rewrite /etc/fstab with the UUIDs of the newly partitioned disks, replacing
//     the stale UUIDs from the capture source.
//  4. Truncate /etc/machine-id so systemd generates a new unique ID on first boot.
//  5. Remove /etc/ssh/ssh_host_* so sshd regenerates host keys on first boot,
//     preventing all deployed nodes from sharing identical host keys.
//
// partDevs must be in the same order as layout.Partitions (index i → device i+1).
func applyBootConfig(ctx context.Context, mountRoot, targetDisk string, layout api.DiskLayout, partDevs []string) error {
	log := logger()

	// ── 0. UEFI EFI binary install (UEFI layouts only) ──────────────────────
	// Rocky Linux ISO-based images are captured from a rootfs where /boot/efi is
	// a mount point stub. The actual EFI binaries (grubx64.efi, shimx64.efi) live
	// on the ESP partition — they are never in the rootfs tar archive. When we
	// partition fresh and format a new ESP, the partition is empty. OVMF then
	// creates a valid NVRAM entry via FixEFIBoot pointing at \EFI\rocky\grubx64.efi,
	// finds nothing on the ESP, and falls back to the boot picker.
	//
	// Fix: if this layout has an ESP (firmware=uefi) and grubx64.efi is absent
	// from the mounted ESP, install grub2-efi-x64 and shim-x64 inside the chroot
	// so their %post scriptlets populate /boot/efi/EFI/rocky/.
	hasESP := false
	for _, p := range layout.Partitions {
		for _, flag := range p.Flags {
			if flag == "esp" || flag == "boot" {
				hasESP = true
				break
			}
		}
	}
	hasBIOSGrubPartition := false
	for _, p := range layout.Partitions {
		for _, flag := range p.Flags {
			if flag == "bios_grub" || flag == "biosboot" {
				hasBIOSGrubPartition = true
				break
			}
		}
	}
	isUEFI := hasESP && !hasBIOSGrubPartition
	if isUEFI {
		grubx64Path := filepath.Join(mountRoot, "boot", "efi", "EFI", "rocky", "grubx64.efi")
		if _, err := os.Stat(grubx64Path); os.IsNotExist(err) {
			log.Warn().Str("path", grubx64Path).
				Msg("finalize/boot: grubx64.efi missing from ESP — ESP was empty after extract; installing grub2-efi-x64 + shim-x64 via dnf in chroot")
			if err := installEFIBootloaderInChroot(ctx, mountRoot); err != nil {
				// Fatal: without grubx64.efi on the ESP, OVMF cannot boot the OS.
				return fmt.Errorf("finalize/boot: EFI bootloader install: %w", err)
			}
			// Log what is now on the ESP.
			espDir := filepath.Join(mountRoot, "boot", "efi", "EFI")
			if entries, readErr := os.ReadDir(espDir); readErr == nil {
				var names []string
				for _, e := range entries {
					names = append(names, e.Name())
				}
				log.Info().Strs("esp_efi_dirs", names).Msg("finalize/boot: ESP EFI/ contents after grub2-efi install")
			}
			// Verify grubx64.efi actually landed.
			if _, err := os.Stat(grubx64Path); os.IsNotExist(err) {
				return fmt.Errorf("finalize/boot: grubx64.efi still absent after grub2-efi-x64 install — dnf scriptlet may have failed")
			}
			log.Info().Str("path", grubx64Path).Msg("finalize/boot: grubx64.efi installed on ESP")
		} else {
			log.Info().Str("path", grubx64Path).Msg("finalize/boot: grubx64.efi already present on ESP — skipping dnf install")
		}
	}

	// ── 1. grub2-mkconfig ────────────────────────────────────────────────────
	// grub2-mkconfig probes /proc and /sys for bootable kernels — it must run
	// inside a chroot with the standard virtual filesystems mounted.
	grubCfgPath := findGrubCfg(mountRoot)
	if grubCfgPath == "" {
		// /boot is empty — the image was captured without /boot contents (common
		// when the source system has /boot on a separate partition and the capture
		// used --one-file-system). Install the kernel and grub2 packages inside the
		// chroot so that grub2-mkconfig has something to build a menu from.
		log.Warn().Str("mountRoot", mountRoot).
			Msg("finalize/boot: grub.cfg not found — /boot is empty; installing kernel + grub2 via dnf in chroot")
		if err := installKernelInChroot(ctx, mountRoot, targetDisk); err != nil {
			return fmt.Errorf("finalize/boot: kernel install: %w", err)
		}
		// Re-check after install.
		grubCfgPath = findGrubCfg(mountRoot)
		if grubCfgPath == "" {
			return fmt.Errorf("finalize/boot: grub.cfg still not found after kernel install — dnf may have failed silently")
		}
	}

	// ── 2. /etc/fstab UUID update (BEFORE grub2-mkconfig) ───────────────────
	// CRITICAL: writeFstab must run BEFORE grub2-mkconfig. grub2-mkconfig reads
	// /etc/fstab inside the chroot to determine the root filesystem UUID for the
	// kernel cmdline (root=UUID=...). If fstab still carries the capture source's
	// UUIDs when grub2-mkconfig runs, the generated grub.cfg will have wrong UUIDs
	// and the deployed node will fail to find its root filesystem on boot.
	//
	// writeFstab uses blkid on the HOST (outside the chroot) against the actual
	// target partition devices — it does not need the chroot session to be active.
	log.Info().Msg("finalize/boot: regenerating /etc/fstab with target disk UUIDs (before grub2-mkconfig)")
	if err := writeFstab(ctx, mountRoot, layout, partDevs); err != nil {
		// Fatal: a missing or incorrect fstab means the root filesystem won't
		// mount and the OS will drop to emergency mode on every boot.
		return fmt.Errorf("finalize/boot: fstab regen: %w", err)
	}
	log.Info().Msg("finalize/boot: /etc/fstab written with target UUIDs")

	// ── 2b. BLS boot entry UUID update ──────────────────────────────────────
	// On Rocky/RHEL 9 with Boot Loader Specification (BLS) enabled, the kernel
	// cmdline — including root=UUID=... — is stored in individual boot entry
	// files under /boot/loader/entries/*.conf, NOT in grub.cfg.
	// grub2-mkconfig reads these entries (via blscfg) but does NOT modify them.
	// The UUID in these files was baked in when the kernel package was installed
	// on the capture source, so it references the source machine's root UUID.
	// We must update each entry's "options" line to reference the target disk's
	// root UUID so the deployed OS can find its root filesystem at boot time.
	//
	// Find the root partition device by matching layout.Partitions[i].MountPoint == "/".
	rootUUID := ""
	for i, p := range layout.Partitions {
		if p.MountPoint == "/" {
			if i < len(partDevs) {
				uuid, err := getUUID(ctx, partDevs[i])
				if err != nil {
					log.Warn().Err(err).Str("device", partDevs[i]).
						Msg("finalize/boot: could not get root UUID for BLS update — deployed OS may fail to boot")
				} else {
					rootUUID = uuid
				}
			}
			break
		}
	}
	if rootUUID != "" {
		// For RAID layouts, add explicit rd.md.uuid= args for each assembled RAID
		// array so dracut can assemble them during early boot. rd.auto is also
		// included as a belt-and-suspenders measure, but rd.md.uuid= is the primary
		// mechanism — it triggers the explicit UUID-based assembly path in
		// dracut's mdraid_start script, which calls mdadm --assemble --scan
		// for any UUIDs not yet assembled by udev.
		//
		// Note: Rocky Linux 10 images don't ship 63-md-raid-arrays.rules or
		// 64-md-raid-assembly.rules (those come from the mdadm package which
		// isn't installed in the capture image). Without those rules, rd.auto's
		// udev-based incremental assembly path doesn't fire. The explicit
		// rd.md.uuid= path in mdraid_start bypasses the udev rules entirely.
		// Always ensure serial console is in the kernel cmdline so that
		// nodes with no VGA output (e.g. single-disk VMs using ttyS0) produce
		// visible output during boot. The argument is idempotent — updateBLSEntries
		// skips any arg already present on the options line.
		blsExtraArgs := []string{"console=ttyS0,115200"}
		if len(layout.RAIDArrays) > 0 {
			blsExtraArgs = append(blsExtraArgs, "rd.auto")
			for _, spec := range layout.RAIDArrays {
				mdDev := "/dev/" + spec.Name
				uuid, uuidErr := getRaidArrayUUID(ctx, mdDev)
				if uuidErr != nil {
					log.Warn().Err(uuidErr).Str("device", mdDev).
						Msg("finalize/boot: could not get RAID array UUID — rd.md.uuid will be missing from kernel cmdline")
				} else if uuid != "" {
					blsExtraArgs = append(blsExtraArgs, "rd.md.uuid="+uuid)
					log.Info().Str("device", mdDev).Str("uuid", uuid).
						Msg("finalize/boot: adding rd.md.uuid to BLS kernel cmdline")
				}
			}
		}
		if err := updateBLSEntries(mountRoot, rootUUID, blsExtraArgs...); err != nil {
			log.Warn().Err(err).Str("root_uuid", rootUUID).
				Msg("finalize/boot: BLS entry update failed — deployed OS may fail to boot (wrong root= in kernel cmdline)")
		} else {
			log.Info().Str("root_uuid", rootUUID).Msg("finalize/boot: BLS boot entries updated with target root UUID")
		}
	} else {
		log.Warn().Msg("finalize/boot: no root partition found in layout — skipping BLS entry update")
	}

	log.Info().Str("grub_cfg", grubCfgPath).Msg("finalize/boot: regenerating GRUB config via grub2-mkconfig")

	// Ensure the standard virtual filesystem mount points exist in the deployed
	// root before calling cs.Enter(). These directories are NOT present in tar
	// archives captured via rsync (rsync skips empty stub directories for virtual
	// mounts like /proc, /sys, /dev). Without them, MountAll fails with ENOENT.
	for _, dir := range []string{"proc", "sys", "dev", "dev/pts", "run"} {
		target := filepath.Join(mountRoot, dir)
		if err := os.MkdirAll(target, 0o755); err != nil {
			log.Warn().Err(err).Str("dir", target).Msg("finalize/boot: could not create chroot mount dir (non-fatal)")
		}
	}

	cs, err := chroot.NewSession(mountRoot)
	if err != nil {
		return fmt.Errorf("finalize/boot: chroot session: %w", err)
	}
	if err := cs.Enter(); err != nil {
		return fmt.Errorf("finalize/boot: chroot enter: %w", err)
	}
	defer func() {
		if cerr := cs.Close(); cerr != nil {
			log.Warn().Err(cerr).Msg("finalize/boot: chroot close error (non-fatal)")
		}
	}()

	// ── BLS machine-id fix ───────────────────────────────────────────────────
	// Rocky/RHEL 9 uses GRUB_ENABLE_BLSCFG=true by default. grub2-mkconfig
	// reads BLS entry files from /boot/loader/entries/*.conf. The BLS entry
	// filenames embed the capture-source machine-id as their prefix, e.g.:
	//   2f0b9a57183b4804a2d55f7c40e9f409-5.14.0-611.5.1.el9_7.x86_64.conf
	// grub2-mkconfig (via /etc/grub.d/10_linux_bls) reads /etc/machine-id and
	// only includes entries whose filename prefix matches the current machine-id.
	// If machine-id is empty (which step 4 below sets it to), no entries match
	// and grub.cfg is generated empty — the node boots to a GRUB rescue shell.
	//
	// Fix: extract the machine-id from an existing BLS entry filename and write
	// it to /etc/machine-id temporarily before grub2-mkconfig runs. After
	// grub2-mkconfig completes, step 4 truncates it so systemd generates a new
	// unique ID on first boot. The grub.cfg itself does not embed machine-id —
	// it only references /boot/loader/entries by filename — so the deployed node
	// gets a fresh identity at first boot while still having a valid GRUB menu.
	blsEntriesDir := filepath.Join(mountRoot, "boot", "loader", "entries")
	if blsEntries, blsErr := os.ReadDir(blsEntriesDir); blsErr == nil {
		for _, blsEntry := range blsEntries {
			name := blsEntry.Name()
			if strings.HasSuffix(name, ".conf") {
				// BLS filename format: <machine-id>-<kernel-version>.conf
				// Machine-id is always exactly 32 hex characters.
				dashIdx := strings.Index(name, "-")
				if dashIdx == 32 {
					sourceMachineID := name[:32]
					machineIDPath := filepath.Join(mountRoot, "etc", "machine-id")
					if writeErr := os.WriteFile(machineIDPath, []byte(sourceMachineID+"\n"), 0o444); writeErr == nil {
						log.Info().Str("machine_id", sourceMachineID).
							Msg("finalize/boot: wrote source machine-id temporarily for grub2-mkconfig BLS lookup")
					} else {
						log.Warn().Err(writeErr).Msg("finalize/boot: failed to write temp machine-id (grub.cfg may be empty)")
					}
					break
				}
			}
		}
	} else {
		log.Warn().Err(blsErr).Str("dir", blsEntriesDir).
			Msg("finalize/boot: could not read BLS entries dir — grub2-mkconfig may produce empty grub.cfg")
	}

	// grub2-mkconfig writes the grub.cfg to the path passed via -o (inside the
	// chroot, so the path is relative to the chroot root). At this point /etc/fstab
	// already has the correct target UUIDs, so grub2-mkconfig will generate the
	// correct root=UUID=... kernel cmdline.
	mkcfgCmd := exec.CommandContext(ctx, "chroot", mountRoot, "grub2-mkconfig", "-o", grubCfgPath)
	if err := runAndLog(ctx, "grub2-mkconfig", mkcfgCmd); err != nil {
		// grub2-mkconfig can fail on RAID layouts because grub2-probe (the disk-probing
		// helper it uses) cannot enumerate md devices via the diskfilter module in the
		// chroot context. When this happens, fall back to patching the existing grub.cfg
		// in-place: replace all UUID references from the capture source with the target
		// partition UUIDs from partDevs. This avoids a full grub2-mkconfig regeneration
		// while still producing a bootable GRUB configuration.
		//
		// On Rocky/RHEL 10 with BLS (GRUB_ENABLE_BLSCFG=true), the grub.cfg body is
		// essentially a UUID-keyed search for /boot + blscfg. All kernel cmdline options
		// (root=UUID=...) live in the BLS .conf files under /boot/loader/entries/, which
		// the code above already updated. Patching the two UUID search calls in grub.cfg
		// is sufficient for a bootable system.
		log.Warn().Err(err).Msg("finalize/boot: grub2-mkconfig failed — attempting in-place UUID patch of existing grub.cfg (RAID fallback)")

		grubCfgAbs := filepath.Join(mountRoot, grubCfgPath)
		if patchErr := patchGrubCfgUUIDs(grubCfgAbs, layout, partDevs); patchErr != nil {
			// Both grub2-mkconfig and the UUID patch failed — the node likely cannot boot.
			return fmt.Errorf("finalize/boot: grub2-mkconfig failed: %w (UUID patch also failed: %v)", err, patchErr)
		}
		log.Info().Str("grub_cfg", grubCfgPath).Msg("finalize/boot: grub.cfg UUID patch complete (grub2-mkconfig fallback applied)")
	} else {
		log.Info().Str("grub_cfg", grubCfgPath).Msg("finalize/boot: grub2-mkconfig complete")
	}

	// ── 2c. Strip save_env / saved_entry from grub.cfg ──────────────────────
	// On BIOS RAID (md devices with diskfilter), GRUB's diskfilter driver is
	// read-only. Any `save_env` or `saved_entry` call in grub.cfg will fail at
	// boot with "diskfilter writes are not supported" and drop the user to a
	// grub> shell before any OS entry is selected. Strip these lines so boot
	// proceeds cleanly. Safe on all layouts — save_env is only used for
	// GRUB_SAVEDEFAULT which we don't need in a clonr-managed environment.
	grubCfgAbs := filepath.Join(mountRoot, grubCfgPath)
	if stripErr := stripGrubSaveEnv(grubCfgAbs); stripErr != nil {
		log.Warn().Err(stripErr).Str("grub_cfg", grubCfgPath).
			Msg("finalize/boot: failed to strip save_env from grub.cfg (non-fatal, but BIOS RAID may drop to grub> shell)")
	} else {
		log.Info().Str("grub_cfg", grubCfgPath).Msg("finalize/boot: save_env/saved_entry lines stripped from grub.cfg")
	}

	// ── 3. dracut --regenerate-all ───────────────────────────────────────────
	// --no-hostonly is critical: the capture source may be bare metal with a
	// specific set of drivers. We need a generic initramfs that includes virtio_blk,
	// virtio_net, and xfs so the image boots on any target (VM or physical).
	// --force overwrites any existing initramfs images without prompting.

	// Ensure /var/tmp exists in the chroot — dracut requires it as a scratch
	// directory. Images captured via rsync may not include empty tmpdir stubs.
	if err := os.MkdirAll(filepath.Join(mountRoot, "var", "tmp"), 0o1777); err != nil {
		log.Warn().Err(err).Msg("finalize/boot: could not create /var/tmp in chroot (non-fatal)")
	}

	// For RAID layouts, ensure the deployed OS initramfs contains the mdraid
	// dracut module so the OS can assemble its md RAID arrays before mounting
	// root on first boot.
	//
	// Two problems must be solved together:
	//
	// 1. dracut module selection: dracut uses host-side device detection to
	//    decide what to include. Since this deploy runs in a minimal initramfs
	//    environment with no md devices, dracut omits the mdraid module unless
	//    forced. We write a drop-in conf to force-include it.
	//
	// 2. mdadm binary: the 90mdraid dracut module's check() function calls
	//    require_binaries mdadm. If mdadm is not installed in the deployed OS
	//    image, the module cannot be installed even when explicitly requested.
	//    We inject the host's mdadm binary into the chroot before running
	//    dracut so the check passes and dracut bundles mdadm into the initramfs.
	//    The injected binary is left in place — mdadm belongs on RAID nodes.
	if len(layout.RAIDArrays) > 0 {
		dracutConfDir := filepath.Join(mountRoot, "etc", "dracut.conf.d")
		if err := os.MkdirAll(dracutConfDir, 0o755); err != nil {
			log.Warn().Err(err).Msg("finalize/boot: could not create /etc/dracut.conf.d in chroot (non-fatal)")
		} else {
			dracutRAIDConf := filepath.Join(dracutConfDir, "10-clonr-mdraid.conf")
			confContent := `# Written by clonr during deployment for RAID layouts.
# Forces mdraid dracut module to be included in the initramfs so the OS can
# assemble its md RAID arrays before mounting root on first boot.
add_dracutmodules+=" mdraid "
# mdadmconf=yes tells dracut to copy /etc/mdadm.conf into the initramfs so
# mdadm can assemble arrays by UUID without requiring rd.md.uuid= cmdline args.
mdadmconf=yes
`
			if err := os.WriteFile(dracutRAIDConf, []byte(confContent), 0o644); err != nil {
				log.Warn().Err(err).Str("path", dracutRAIDConf).
					Msg("finalize/boot: could not write mdraid dracut config — initramfs may not include RAID support")
			} else {
				log.Info().Str("path", dracutRAIDConf).
					Msg("finalize/boot: wrote mdraid dracut config — RAID support will be included in initramfs")
			}
		}

		// Inject mdadm into the chroot if the deployed image does not have it.
		// dracut's 90mdraid module check() calls require_binaries mdadm — if the
		// binary is absent, dracut refuses to install the module even when explicitly
		// requested via add_dracutmodules. We copy the host mdadm binary so dracut
		// can find it and embed it in the rebuilt initramfs.
		chrootMdadm := filepath.Join(mountRoot, "usr", "sbin", "mdadm")
		if _, err := os.Stat(chrootMdadm); os.IsNotExist(err) {
			// Find mdadm on the host (clonr deploy environment).
			hostMdadm, lookErr := exec.LookPath("mdadm")
			if lookErr != nil {
				log.Warn().Msg("finalize/boot: mdadm not found on deploy host — dracut mdraid module may fail to install")
			} else {
				if copyErr := copyFile(hostMdadm, chrootMdadm, 0o755); copyErr != nil {
					log.Warn().Err(copyErr).Str("src", hostMdadm).Str("dst", chrootMdadm).
						Msg("finalize/boot: could not inject mdadm into chroot — dracut mdraid module may fail to install")
				} else {
					log.Info().Str("src", hostMdadm).Str("dst", chrootMdadm).
						Msg("finalize/boot: injected mdadm into chroot for dracut mdraid module")
				}
			}
		} else {
			log.Info().Str("path", chrootMdadm).
				Msg("finalize/boot: mdadm already present in chroot — skipping injection")
		}

		// Inject mdadm udev rules into the chroot so dracut's 90mdraid module
		// can install them into the initramfs. Without these rules the RAID arrays
		// assemble correctly but udev never creates the /dev/disk/by-id/md-uuid-*
		// symlinks that dracut's initqueue finished-hooks wait for, causing a
		// timeout and emergency shell even when the root array is actually healthy.
		//
		// dracut's 90mdraid/module-setup.sh calls `inst_rules 63-md-raid-arrays.rules`
		// which looks for the rule in the chroot's /usr/lib/udev/rules.d/. If absent
		// (because mdadm isn't installed in the captured OS image), dracut silently
		// skips it and the initramfs lacks the symlink-creation rules.
		//
		// The rule content is embedded directly rather than copied from the deploy
		// host so this works regardless of what is installed in the PXE environment.
		// The content matches the canonical mdadm udev rules for RHEL/Rocky Linux.
		chrootUdevRulesDir := filepath.Join(mountRoot, "usr", "lib", "udev", "rules.d")
		if mkdirErr := os.MkdirAll(chrootUdevRulesDir, 0o755); mkdirErr != nil {
			log.Warn().Err(mkdirErr).Msg("finalize/boot: could not create udev rules.d in chroot (non-fatal)")
		} else {
			for _, ruleSpec := range []struct {
				name    string
				content string
			}{
				{
					name:    "63-md-raid-arrays.rules",
					content: mdRaidArraysRules,
				},
				{
					name:    "64-md-raid-assembly.rules",
					content: mdRaidAssemblyRules,
				},
			} {
				chrootRule := filepath.Join(chrootUdevRulesDir, ruleSpec.name)
				if _, statErr := os.Stat(chrootRule); statErr == nil {
					// Already present in the deployed OS — leave the OS version in place.
					log.Info().Str("file", ruleSpec.name).
						Msg("finalize/boot: mdadm udev rule already present in chroot — skipping injection")
					continue
				}
				if writeErr := os.WriteFile(chrootRule, []byte(ruleSpec.content), 0o644); writeErr != nil {
					log.Warn().Err(writeErr).Str("dst", chrootRule).
						Msg("finalize/boot: could not write mdadm udev rule into chroot (non-fatal)")
				} else {
					log.Info().Str("file", ruleSpec.name).
						Msg("finalize/boot: wrote mdadm udev rule into chroot for dracut mdraid module")
				}
			}
		}
	}

	log.Info().Msg("finalize/boot: regenerating initramfs via dracut --no-hostonly --regenerate-all")
	dracutCmd := exec.CommandContext(ctx, "chroot", mountRoot,
		"dracut", "--force", "--no-hostonly", "--regenerate-all")
	if err := runAndLog(ctx, "dracut", dracutCmd); err != nil {
		// Non-fatal: the node may still boot if the capture source's initramfs
		// happens to contain the required drivers. Log loudly so the operator
		// knows to investigate if the node kernel-panics on boot.
		log.Warn().Err(err).
			Msg("WARNING finalize/boot: dracut --regenerate-all failed — initramfs may lack hardware drivers for target; node may not boot on different hardware")
	} else {
		log.Info().Msg("finalize/boot: dracut complete")
	}

	// ── 4. machine-id scrub ──────────────────────────────────────────────────
	// systemd uses /etc/machine-id as a stable unique identifier for the host.
	// A non-empty machine-id baked into the image would be shared by every node
	// deployed from it. Truncating (not removing) the file causes systemd to
	// generate a new ID on first boot and write it back.
	machineIDPath := filepath.Join(mountRoot, "etc", "machine-id")
	// Mode 0644: must be writable so systemd-machine-id-setup can write the new ID
	// on first boot. The previous 0444 (read-only) prevented systemd from updating
	// the file, leaving the machine-id empty and causing sshd-keygen to fail.
	if err := os.WriteFile(machineIDPath, []byte{}, 0o644); err != nil {
		log.Warn().Err(err).Str("path", machineIDPath).
			Msg("finalize/boot: could not truncate machine-id (non-fatal)")
	} else {
		log.Info().Msg("finalize/boot: machine-id truncated — new ID will be generated on first boot")
	}

	// ── 5. SSH host key scrub ────────────────────────────────────────────────
	// Host keys baked into the image would be identical on every deployed node,
	// making MITM attacks trivial. Remove them so sshd regenerates unique keys
	// on first boot via the ssh-keygen firstboot unit.
	hostKeys, _ := filepath.Glob(filepath.Join(mountRoot, "etc", "ssh", "ssh_host_*"))
	for _, k := range hostKeys {
		if err := os.Remove(k); err != nil {
			log.Warn().Err(err).Str("key", k).
				Msg("finalize/boot: could not remove SSH host key (non-fatal)")
		}
	}
	if len(hostKeys) > 0 {
		log.Info().Int("count", len(hostKeys)).
			Msg("finalize/boot: SSH host keys removed — sshd will regenerate on first boot")
	}

	return nil
}

// stripGrubSaveEnv removes `save_env` and `saved_entry` calls from a grub.cfg
// file. On BIOS RAID systems that use the diskfilter module the GRUB environment
// block is read-only; any write attempt produces "diskfilter writes are not
// supported" and drops the user to a grub> rescue shell before the OS boots.
// Stripping these lines is safe on all layouts: save_env is only relevant for
// GRUB_SAVEDEFAULT (remember the last-booted entry), which clonr does not use.
func stripGrubSaveEnv(grubCfgAbs string) error {
	data, err := os.ReadFile(grubCfgAbs)
	if err != nil {
		return fmt.Errorf("read grub.cfg: %w", err)
	}

	var out []string
	stripped := 0
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "save_env") || strings.HasPrefix(trimmed, "saved_entry") {
			stripped++
			continue
		}
		out = append(out, line)
	}
	if stripped == 0 {
		// Nothing to strip — file is already clean.
		return nil
	}

	content := strings.Join(out, "\n")
	if err := os.WriteFile(grubCfgAbs, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write grub.cfg: %w", err)
	}
	logger().Info().Int("lines_stripped", stripped).Str("path", grubCfgAbs).
		Msg("finalize/boot: stripped save_env/saved_entry lines from grub.cfg")
	return nil
}

// patchGrubCfgUUIDs is the fallback path for when grub2-mkconfig cannot run
// (e.g. on RAID layouts where grub2-probe fails to enumerate md devices).
//
// It reads the existing grub.cfg, extracts all UUID= strings that appear in
// search/fs-uuid directives or root= cmdlines, maps them to target partition
// UUIDs by matching mount points via fstab/blkid, and replaces them in-place.
//
// On Rocky/RHEL 10 with BLS the grub.cfg body is minimal: it contains a
// `search --fs-uuid` for the /boot partition UUID and a `blscfg` call. The
// kernel root=UUID= lives in the BLS .conf files (updated by updateBLSEntries).
// Patching the /boot UUID reference in grub.cfg is sufficient for booting.
func patchGrubCfgUUIDs(grubCfgAbs string, layout api.DiskLayout, partDevs []string) error {
	log := logger()

	data, err := os.ReadFile(grubCfgAbs)
	if err != nil {
		return fmt.Errorf("read grub.cfg: %w", err)
	}
	original := string(data)

	// Build a map from old UUID → new UUID by scanning the live partition devices.
	// grub.cfg embeds UUIDs from the capture source — we must replace ALL of them.
	uuidRe := regexp.MustCompile(`[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}`)
	ctx := context.Background()

	// Collect old UUIDs from grub.cfg.
	oldUUIDs := make(map[string]bool)
	for _, u := range uuidRe.FindAllString(original, -1) {
		oldUUIDs[u] = true
	}
	if len(oldUUIDs) == 0 {
		log.Info().Msg("finalize/boot: grub.cfg has no UUID references — nothing to patch")
		return nil
	}

	// Collect new UUIDs from target partitions, keyed by mountpoint.
	type newUUIDEntry struct {
		uuid string
		mp   string
	}
	var newEntries []newUUIDEntry
	for i, p := range layout.Partitions {
		if p.MountPoint == "" || p.Filesystem == "" || p.Filesystem == "biosboot" || p.Filesystem == "bios_grub" {
			continue
		}
		if i >= len(partDevs) {
			continue
		}
		uuid, uuidErr := getUUID(ctx, partDevs[i])
		if uuidErr != nil {
			log.Warn().Err(uuidErr).Str("dev", partDevs[i]).Msg("finalize/boot: grub.cfg UUID patch — cannot get UUID for partition")
			continue
		}
		newEntries = append(newEntries, newUUIDEntry{uuid: uuid, mp: p.MountPoint})
	}

	if len(newEntries) == 0 {
		return fmt.Errorf("no target partition UUIDs available for grub.cfg patching")
	}

	// Replace old UUIDs with new ones. The primary goal is to fix the
	// `search --no-floppy --fs-uuid --set=root <UUID>` lines which tell GRUB
	// where to find /boot. On Rocky/RHEL 10 with BLS, the kernel root= UUID
	// lives in the BLS .conf files (updated by updateBLSEntries above), so we
	// only NEED to fix the /boot search UUID. Any kernelopts UUID in grub.cfg
	// is a fallback for entries without a BLS options line and does not affect
	// Rocky 10 BLS-based boots.
	//
	// Strategy:
	//   1. Find UUIDs that appear specifically in `search --fs-uuid` lines —
	//      these are definitively the /boot UUID (or / UUID for non-BLS grub.cfg).
	//      Replace each with the new /boot UUID.
	//   2. For any remaining old UUIDs (e.g. kernelopts fallback, root= in
	//      legacy menuentry), replace with the most appropriate new UUID by
	//      mount point preference (/boot > / > first).
	patched := original

	// Find the new /boot UUID (and / UUID as fallback).
	var newBootUUID, newRootUUID string
	for _, e := range newEntries {
		if e.mp == "/boot" || e.mp == "/boot/efi" {
			newBootUUID = e.uuid
		}
		if e.mp == "/" {
			newRootUUID = e.uuid
		}
	}
	if newBootUUID == "" {
		// No explicit /boot partition — use root as the boot device.
		newBootUUID = newRootUUID
	}
	if newBootUUID == "" && len(newEntries) > 0 {
		newBootUUID = newEntries[0].uuid
	}

	// Identify UUIDs in search --fs-uuid lines.
	searchUUIDRe := regexp.MustCompile(`search\s+--no-floppy\s+--fs-uuid\s+(?:--set=\w+\s+)?(?:--hint[^\s]+\s+)?(\S+)`)
	searchUUIDs := make(map[string]bool)
	for _, m := range searchUUIDRe.FindAllStringSubmatch(original, -1) {
		if len(m) > 1 && uuidRe.MatchString(m[1]) {
			searchUUIDs[m[1]] = true
		}
	}

	// Replace search UUIDs with the new /boot UUID.
	for oldUUID := range searchUUIDs {
		patched = strings.ReplaceAll(patched, oldUUID, newBootUUID)
		log.Info().Str("old", oldUUID).Str("new", newBootUUID).
			Msg("finalize/boot: grub.cfg UUID patched (search --fs-uuid → /boot UUID)")
	}

	// Replace any remaining old UUIDs (kernelopts fallback, legacy menuentry root=).
	// Use /boot UUID for /boot-related UUIDs and root UUID for others (heuristic).
	for oldUUID := range oldUUIDs {
		if searchUUIDs[oldUUID] {
			continue // already patched above
		}
		// For non-search UUIDs, use root UUID if known, otherwise boot UUID.
		replacement := newRootUUID
		if replacement == "" {
			replacement = newBootUUID
		}
		if replacement != "" && strings.Contains(patched, oldUUID) {
			patched = strings.ReplaceAll(patched, oldUUID, replacement)
			log.Info().Str("old", oldUUID).Str("new", replacement).
				Msg("finalize/boot: grub.cfg UUID patched (non-search UUID → root UUID)")
		}
	}

	if patched == original {
		log.Warn().Msg("finalize/boot: grub.cfg UUID patch made no changes — grub.cfg may use non-standard UUID references")
	}

	if err := os.WriteFile(grubCfgAbs, []byte(patched), 0o644); err != nil {
		return fmt.Errorf("write grub.cfg: %w", err)
	}
	log.Info().Str("path", grubCfgAbs).Msg("finalize/boot: grub.cfg written with patched UUIDs")
	return nil
}

// updateBLSEntries rewrites the root=UUID=... argument in every Boot Loader
// Specification (BLS) entry under /boot/loader/entries/*.conf so that the
// kernel cmdline references the target disk's root filesystem UUID rather than
// the capture source's UUID. extraArgs is appended to the options line of each
// entry if not already present (e.g. "rd.auto" for RAID layouts).
//
// On Rocky/RHEL 9 with blscfg, GRUB reads kernel cmdlines from these .conf
// files. grub2-mkconfig does not modify them — they are managed by kernel-install
// and grubby. Without this fix, the deployed OS kernel panics with
// "Unable to find root filesystem" because it tries to mount the OLD UUID.
func updateBLSEntries(mountRoot, rootUUID string, extraArgs ...string) error {
	log := logger()
	entriesDir := filepath.Join(mountRoot, "boot", "loader", "entries")

	// Glob all BLS entries.
	entries, err := filepath.Glob(filepath.Join(entriesDir, "*.conf"))
	if err != nil || len(entries) == 0 {
		// Not a BLS system, or /boot/loader/entries doesn't exist.
		// This is non-fatal — the system may use a legacy grub.cfg directly.
		log.Info().Str("dir", entriesDir).Msg("finalize/boot: no BLS entries found — skipping BLS UUID update (non-BLS system)")
		return nil
	}

	uuidRe := regexp.MustCompile(`root=UUID=[0-9a-fA-F-]+`)
	updated := 0
	for _, path := range entries {
		data, err := os.ReadFile(path)
		if err != nil {
			log.Warn().Err(err).Str("path", path).Msg("finalize/boot: could not read BLS entry")
			continue
		}

		original := string(data)
		// Replace any existing root=UUID=... on the "options" line.
		newContent := uuidRe.ReplaceAllString(original, "root=UUID="+rootUUID)

		// Append extraArgs to "options" line if not already present.
		for _, arg := range extraArgs {
			newLines := strings.Split(newContent, "\n")
			for i, line := range newLines {
				if strings.HasPrefix(line, "options ") && !strings.Contains(line, arg) {
					newLines[i] = strings.TrimRight(line, " ") + " " + arg
				}
			}
			newContent = strings.Join(newLines, "\n")
		}

		if newContent == original {
			// No changes needed — already up to date.
			continue
		}

		if err := os.WriteFile(path, []byte(newContent), 0o644); err != nil {
			log.Warn().Err(err).Str("path", path).Msg("finalize/boot: could not write BLS entry")
			continue
		}
		log.Info().Str("path", filepath.Base(path)).Str("root_uuid", rootUUID).
			Msg("finalize/boot: updated root UUID in BLS entry")
		updated++
	}

	if updated == 0 && len(entries) > 0 {
		log.Warn().Str("dir", entriesDir).
			Msg("finalize/boot: BLS entries found but none had root=UUID= — may already be correct or using non-standard cmdline")
	}
	return nil
}

// getUUID returns the filesystem UUID of a block device using blkid.
// Returns an error if blkid is unavailable or the device has no UUID (e.g.
// unformatted or a bios_grub partition).
func getUUID(ctx context.Context, device string) (string, error) {
	out, err := exec.CommandContext(ctx, "blkid", "-s", "UUID", "-o", "value", device).Output()
	if err != nil {
		return "", fmt.Errorf("blkid %s: %w", device, err)
	}
	uuid := strings.TrimSpace(string(out))
	if uuid == "" {
		return "", fmt.Errorf("blkid %s: no UUID (partition may be unformatted)", device)
	}
	return uuid, nil
}

// writeFstab generates /etc/fstab for the deployed filesystem from the actual
// UUIDs of the target partitions. It replaces whatever fstab the image carried
// from the capture source, which has the source system's UUIDs.
//
// Only partitions with a non-empty MountPoint and a formattable filesystem are
// written. biosboot/bios_grub partitions are silently skipped.
func writeFstab(ctx context.Context, mountRoot string, layout api.DiskLayout, partDevs []string) error {
	log := logger()

	var sb strings.Builder
	sb.WriteString("# /etc/fstab — generated by clonr during deployment\n")
	sb.WriteString("# <device>  <mountpoint>  <fstype>  <options>  <dump>  <pass>\n\n")

	for i, p := range layout.Partitions {
		if p.MountPoint == "" {
			continue // biosboot, unpartitioned, or no mount needed
		}
		switch p.Filesystem {
		case "", "biosboot", "bios_grub":
			continue // no filesystem, nothing to mount
		}

		if i >= len(partDevs) {
			log.Warn().Int("partition", i+1).Msg("writeFstab: partDevs slice shorter than layout — skipping")
			continue
		}
		dev := partDevs[i]

		uuid, err := getUUID(ctx, dev)
		if err != nil {
			// If we can't get a UUID the fstab entry would be useless and the
			// node would fail to boot. Return an error so Finalize aborts cleanly
			// rather than deploying a machine that will boot-loop.
			return fmt.Errorf("partition %d (%s): %w", i+1, dev, err)
		}

		// Standard mount options per filesystem and mountpoint.
		opts := fstabMountOpts(p.Filesystem, p.MountPoint)

		// dump/pass: root gets pass=1, /boot gets pass=2, everything else 0.
		dump := 0
		pass := 0
		switch p.MountPoint {
		case "/":
			dump, pass = 1, 1
		case "/boot":
			dump, pass = 1, 2
		}

		if p.Filesystem == "swap" {
			fmt.Fprintf(&sb, "UUID=%-36s  %-12s  %-6s  %-20s  %d  %d\n",
				uuid, "swap", "swap", "defaults", 0, 0)
		} else {
			fmt.Fprintf(&sb, "UUID=%-36s  %-12s  %-6s  %-20s  %d  %d\n",
				uuid, p.MountPoint, p.Filesystem, opts, dump, pass)
		}

		log.Info().Str("uuid", uuid).Str("mountpoint", p.MountPoint).
			Str("device", dev).Msg("finalize/boot: fstab entry written")
	}

	fstabPath := filepath.Join(mountRoot, "etc", "fstab")
	if err := os.WriteFile(fstabPath, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("write fstab: %w", err)
	}
	return nil
}

// fstabMountOpts returns appropriate mount options for a given filesystem type
// and mountpoint. These are conservative production defaults for Rocky Linux 9.
func fstabMountOpts(fstype, mountpoint string) string {
	switch fstype {
	case "xfs":
		if mountpoint == "/" {
			return "defaults,noatime"
		}
		return "defaults"
	case "ext4":
		if mountpoint == "/" {
			return "defaults,noatime"
		}
		return "defaults"
	case "vfat", "fat32":
		return "defaults,uid=0,gid=0,umask=077,shortname=winnt"
	case "swap":
		return "defaults"
	default:
		return "defaults"
	}
}

// applyExtraMounts appends custom fstab entries from NodeConfig.ExtraMounts and
// optionally creates the mount point directories inside the deployed filesystem.
// It must be called after applyBootConfig so the base fstab already exists.
//
// Invalid entries are skipped with a warning rather than aborting the deployment,
// because a bad shared-storage entry should not prevent the node from booting.
func applyExtraMounts(ctx context.Context, mountRoot string, mounts []api.FstabEntry) error {
	if len(mounts) == 0 {
		return nil
	}

	log := logger()

	fstabPath := filepath.Join(mountRoot, "etc", "fstab")
	f, err := os.OpenFile(fstabPath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return fmt.Errorf("applyExtraMounts: open fstab: %w", err)
	}
	defer f.Close()

	fmt.Fprintf(f, "\n# Additional mounts from clonr NodeConfig.ExtraMounts\n")

	written := 0
	for _, m := range mounts {
		if err := api.ValidateFstabEntry(m); err != nil {
			log.Warn().Err(err).Str("mount_point", m.MountPoint).
				Msg("finalize: skipping invalid extra fstab entry")
			continue
		}

		// Auto-create the mount point directory inside the deployed filesystem.
		if m.AutoMkdir {
			targetDir := filepath.Join(mountRoot, m.MountPoint)

			// Path traversal guard: the resolved absolute path must remain inside mountRoot.
			absTarget, err := filepath.Abs(targetDir)
			if err != nil || !strings.HasPrefix(absTarget, mountRoot+string(filepath.Separator)) {
				log.Warn().Str("mount_point", m.MountPoint).
					Msg("finalize: mount point escapes deployed filesystem root — skipping mkdir")
			} else if err := os.MkdirAll(absTarget, 0755); err != nil {
				// Non-fatal: the mount will fail at boot, but we still write the entry
				// so the operator can investigate rather than silently losing the config.
				log.Warn().Err(err).Str("path", absTarget).
					Msg("finalize: failed to create extra mount point (non-fatal)")
			} else {
				log.Info().Str("path", m.MountPoint).
					Msg("finalize: created mount point for extra mount")
			}
		}

		// Resolve mount options: default to "defaults" when empty, then auto-inject
		// _netdev for network filesystems that omit it (needed so systemd waits for
		// the network before attempting the mount).
		opts := m.Options
		if opts == "" {
			opts = "defaults"
		}
		if api.IsNetworkFS(m.FSType) && !strings.Contains(opts, "_netdev") {
			opts += ",_netdev"
			log.Info().Str("fs_type", m.FSType).Str("mount_point", m.MountPoint).
				Msg("finalize: auto-added _netdev to extra mount options for network filesystem")
		}

		if m.Comment != "" {
			fmt.Fprintf(f, "# %s\n", m.Comment)
		}
		// fstab format: source  mountpoint  fstype  options  dump  pass
		fmt.Fprintf(f, "%s\t%s\t%s\t%s\t%d\t%d\n",
			m.Source, m.MountPoint, m.FSType, opts, m.Dump, m.Pass)

		log.Info().
			Str("source", m.Source).
			Str("mount_point", m.MountPoint).
			Str("fs_type", m.FSType).
			Msg("finalize: wrote extra fstab entry")
		written++
	}

	log.Info().Int("count", written).Msg("finalize: extra fstab entries written")
	return nil
}

// getRaidArrayUUID returns the UUID of an assembled md RAID array in the
// colon-separated format used by dracut's rd.md.uuid= kernel cmdline parameter
// (e.g. "3c483b47:8a550722:e7c1e792:d426519c").
// It runs "mdadm --detail --export <device>" and extracts the MD_UUID field.
func getRaidArrayUUID(ctx context.Context, mdDev string) (string, error) {
	out, err := exec.CommandContext(ctx, "mdadm", "--detail", "--export", mdDev).Output()
	if err != nil {
		return "", fmt.Errorf("mdadm --detail --export %s: %w", mdDev, err)
	}
	for _, line := range strings.Split(string(out), "\n") {
		if strings.HasPrefix(line, "MD_UUID=") {
			return strings.TrimPrefix(line, "MD_UUID="), nil
		}
	}
	return "", fmt.Errorf("MD_UUID not found in mdadm --detail --export output for %s", mdDev)
}

// copyFile copies src to dst with the given permission bits.
// If dst's parent directory does not exist it is created.
func copyFile(src, dst string, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return fmt.Errorf("copyFile: mkdir: %w", err)
	}
	in, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("copyFile: open src: %w", err)
	}
	defer in.Close()

	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, perm)
	if err != nil {
		return fmt.Errorf("copyFile: open dst: %w", err)
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return fmt.Errorf("copyFile: copy: %w", err)
	}
	return nil
}
