package handlers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
	"github.com/sqoia-dev/clonr/pkg/api"
	"github.com/sqoia-dev/clonr/pkg/db"
)

// autoHostnameRe matches hostnames that were auto-generated by clonr.
// Pattern: clonr-<4 hex digits>, e.g. "clonr-e92f".
var autoHostnameRe = regexp.MustCompile(`^clonr-[0-9a-f]{4}$`)

// defaultDomain returns the domain to use when building auto-generated FQDNs.
// Override by setting the CLONR_DEFAULT_DOMAIN environment variable.
func defaultDomain() string {
	if d := os.Getenv("CLONR_DEFAULT_DOMAIN"); d != "" {
		return d
	}
	return "clonr.local"
}

// autoHostname generates a deterministic hostname from the last 4 hex chars of
// the MAC address (colons stripped). E.g. "bc:24:11:36:e9:2f" → "clonr-e92f".
func autoHostname(mac string) string {
	stripped := strings.ReplaceAll(mac, ":", "")
	if len(stripped) >= 4 {
		return "clonr-" + stripped[len(stripped)-4:]
	}
	return "clonr-" + stripped
}

// NodesHandler handles all /api/v1/nodes routes.
type NodesHandler struct {
	DB *db.DB
}

// sanitizeNodeConfig returns cfg with sensitive fields in PowerProvider redacted.
// Call this on every outbound NodeConfig so credentials never leak in responses.
func sanitizeNodeConfig(cfg api.NodeConfig) api.NodeConfig {
	cfg.PowerProvider = cfg.PowerProvider.Sanitize()
	return cfg
}

// sanitizeNodeConfigs applies sanitizeNodeConfig to a slice in place.
func sanitizeNodeConfigs(cfgs []api.NodeConfig) []api.NodeConfig {
	for i := range cfgs {
		cfgs[i] = sanitizeNodeConfig(cfgs[i])
	}
	return cfgs
}

// ListNodes handles GET /api/v1/nodes
func (h *NodesHandler) ListNodes(w http.ResponseWriter, r *http.Request) {
	baseImageID := r.URL.Query().Get("base_image_id")
	nodes, err := h.DB.ListNodeConfigs(r.Context(), baseImageID)
	if err != nil {
		log.Error().Err(err).Msg("list nodes")
		writeError(w, err)
		return
	}
	if nodes == nil {
		nodes = []api.NodeConfig{}
	}
	nodes = sanitizeNodeConfigs(nodes)
	writeJSON(w, http.StatusOK, api.ListNodesResponse{Nodes: nodes, Total: len(nodes)})
}

// CreateNode handles POST /api/v1/nodes
func (h *NodesHandler) CreateNode(w http.ResponseWriter, r *http.Request) {
	var req api.CreateNodeConfigRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeValidationError(w, "invalid JSON body")
		return
	}

	if req.Hostname == "" {
		writeValidationError(w, "hostname is required")
		return
	}
	if req.PrimaryMAC == "" {
		writeValidationError(w, "primary_mac is required")
		return
	}
	if req.BaseImageID == "" {
		writeValidationError(w, "base_image_id is required")
		return
	}

	now := time.Now().UTC()
	cfg := api.NodeConfig{
		ID:          uuid.New().String(),
		Hostname:    req.Hostname,
		FQDN:        req.FQDN,
		PrimaryMAC:  req.PrimaryMAC,
		Interfaces:  req.Interfaces,
		SSHKeys:     req.SSHKeys,
		KernelArgs:  req.KernelArgs,
		Groups:      req.Groups,
		CustomVars:  req.CustomVars,
		BaseImageID: req.BaseImageID,
		CreatedAt:   now,
		UpdatedAt:   now,
	}
	if cfg.Interfaces == nil {
		cfg.Interfaces = []api.InterfaceConfig{}
	}
	if cfg.SSHKeys == nil {
		cfg.SSHKeys = []string{}
	}
	if cfg.Groups == nil {
		cfg.Groups = []string{}
	}
	if cfg.CustomVars == nil {
		cfg.CustomVars = map[string]string{}
	}

	if err := h.DB.CreateNodeConfig(r.Context(), cfg); err != nil {
		log.Error().Err(err).Msg("create node config")
		writeError(w, err)
		return
	}

	writeJSON(w, http.StatusCreated, cfg)
}

// GetNode handles GET /api/v1/nodes/:id
func (h *NodesHandler) GetNode(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	cfg, err := h.DB.GetNodeConfig(r.Context(), id)
	if err != nil {
		writeError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, sanitizeNodeConfig(cfg))
}

// UpdateNode handles PUT /api/v1/nodes/:id
func (h *NodesHandler) UpdateNode(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	var req api.UpdateNodeConfigRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeValidationError(w, "invalid JSON body")
		return
	}

	if req.Hostname == "" {
		writeValidationError(w, "hostname is required")
		return
	}
	if req.PrimaryMAC == "" {
		writeValidationError(w, "primary_mac is required")
		return
	}

	// Fetch to confirm existence.
	existing, err := h.DB.GetNodeConfig(r.Context(), id)
	if err != nil {
		writeError(w, err)
		return
	}

	// Validate extra mount entries before touching the database.
	for i, m := range req.ExtraMounts {
		if err := api.ValidateFstabEntry(m); err != nil {
			writeValidationError(w, fmt.Sprintf("extra_mounts[%d]: %s", i, err.Error()))
			return
		}
	}

	// Resolve the layout override:
	//   - ClearLayoutOverride=true  → explicitly remove override (set nil)
	//   - DiskLayoutOverride present in request → use the new value
	//   - Neither present (omitempty field absent) → preserve existing override
	//     so that a PUT to change hostname/image does not silently wipe a
	//     node-level disk layout that was set via the dedicated override endpoint.
	var layoutOverride *api.DiskLayout
	switch {
	case req.ClearLayoutOverride:
		layoutOverride = nil // explicit clear
	case req.DiskLayoutOverride != nil:
		layoutOverride = req.DiskLayoutOverride // caller supplied a new override
	default:
		layoutOverride = existing.DiskLayoutOverride // preserve existing
	}
	// Preserve the existing group assignment unless explicitly changed in the request.
	groupID := existing.GroupID
	if req.GroupID != "" || req.GroupID == "" && existing.GroupID != "" {
		groupID = req.GroupID
	}

	cfg := api.NodeConfig{
		ID:                 id,
		Hostname:           req.Hostname,
		HostnameAuto:       false, // admin explicitly set the hostname → mark as non-auto
		FQDN:               req.FQDN,
		PrimaryMAC:         req.PrimaryMAC,
		Interfaces:         req.Interfaces,
		SSHKeys:            req.SSHKeys,
		KernelArgs:         req.KernelArgs,
		Groups:             req.Groups,
		CustomVars:         req.CustomVars,
		BaseImageID:        req.BaseImageID,
		PowerProvider:      req.PowerProvider,
		GroupID:            groupID,
		DiskLayoutOverride: layoutOverride,
		ExtraMounts:        req.ExtraMounts,
		CreatedAt:          existing.CreatedAt,
		UpdatedAt:          time.Now().UTC(),
	}
	if cfg.Interfaces == nil {
		cfg.Interfaces = []api.InterfaceConfig{}
	}
	if cfg.SSHKeys == nil {
		cfg.SSHKeys = []string{}
	}
	if cfg.Groups == nil {
		cfg.Groups = []string{}
	}
	if cfg.CustomVars == nil {
		cfg.CustomVars = map[string]string{}
	}

	if err := h.DB.UpdateNodeConfig(r.Context(), cfg); err != nil {
		log.Error().Err(err).Msg("update node config")
		writeError(w, err)
		return
	}

	writeJSON(w, http.StatusOK, cfg)
}

// DeleteNode handles DELETE /api/v1/nodes/:id
func (h *NodesHandler) DeleteNode(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	if err := h.DB.DeleteNodeConfig(r.Context(), id); err != nil {
		writeError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// GetNodeByMAC handles GET /api/v1/nodes/by-mac/:mac
func (h *NodesHandler) GetNodeByMAC(w http.ResponseWriter, r *http.Request) {
	mac := chi.URLParam(r, "mac")
	cfg, err := h.DB.GetNodeConfigByMAC(r.Context(), mac)
	if err != nil {
		writeError(w, err)
		return
	}
	// Pre-merge group extra mounts so the deploy client receives the full
	// effective mount list in ExtraMounts without needing a separate group lookup.
	cfg = mergeGroupExtraMounts(r.Context(), h.DB, cfg)
	writeJSON(w, http.StatusOK, sanitizeNodeConfig(cfg))
}

// RegisterNode handles POST /api/v1/nodes/register.
// Called by the clonr client on first PXE boot. Creates a NodeConfig stub if
// the MAC is new, or updates the hardware_profile if the node already exists.
// Returns the NodeConfig and an action directive ("deploy" or "wait").
func (h *NodesHandler) RegisterNode(w http.ResponseWriter, r *http.Request) {
	const maxRegisterBodyBytes = 1 << 20 // 1 MiB
	r.Body = http.MaxBytesReader(w, r.Body, maxRegisterBodyBytes)

	var req api.RegisterRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		if err.Error() == "http: request body too large" {
			http.Error(w, "request body too large (max 1MB)", http.StatusRequestEntityTooLarge)
			return
		}
		writeValidationError(w, "invalid JSON body")
		return
	}

	if len(req.HardwareProfile) == 0 {
		writeValidationError(w, "hardware_profile is required")
		return
	}

	// Extract primary MAC and hostname from the hardware profile.
	primaryMAC, hwHostname := extractNodeIdentity(req.HardwareProfile)
	if primaryMAC == "" {
		writeValidationError(w, "hardware_profile must contain at least one NIC with a MAC address")
		return
	}

	// Determine the hostname for this registration pass.
	// Priority: hardware-reported hostname > auto-generated.
	// Auto-generation only applies when the hardware profile carries no hostname.
	hostname := hwHostname
	hostnameAuto := false
	if hostname == "" {
		hostname = autoHostname(primaryMAC)
		hostnameAuto = true
		log.Info().Str("mac", primaryMAC).Str("hostname", hostname).
			Msg("register node: auto-generated hostname")
	}

	// Build FQDN for new nodes when none is reported by hardware.
	fqdn := hostname + "." + defaultDomain()

	now := time.Now().UTC()
	stub := api.NodeConfig{
		ID:              uuid.New().String(),
		Hostname:        hostname,
		HostnameAuto:    hostnameAuto,
		FQDN:            fqdn,
		PrimaryMAC:      primaryMAC,
		Interfaces:      []api.InterfaceConfig{},
		SSHKeys:         []string{},
		Groups:          []string{},
		CustomVars:      map[string]string{},
		HardwareProfile: req.HardwareProfile,
		CreatedAt:       now,
		UpdatedAt:       now,
	}

	nodeCfg, err := h.DB.UpsertNodeByMAC(r.Context(), stub)
	if err != nil {
		log.Error().Err(err).Str("mac", primaryMAC).Msg("register node: upsert failed")
		writeError(w, err)
		return
	}

	action := "wait"
	if nodeCfg.BaseImageID != "" {
		action = "deploy"
	}
	// A pending reimage overrides the normal wait/deploy logic: always deploy.
	// The reimage orchestrator set this flag after firing SetNextBoot(PXE) +
	// PowerCycle — the node is here because it was told to come back for a
	// fresh image.
	var dryRun bool
	if nodeCfg.ReimagePending {
		action = "deploy"
		// Look up the active reimage request to surface dry_run to the client.
		if activeReq, err := h.DB.GetActiveReimageForNode(r.Context(), nodeCfg.ID); err == nil && activeReq != nil {
			dryRun = activeReq.DryRun
		}
	}

	log.Info().Str("mac", primaryMAC).Str("hostname", nodeCfg.Hostname).
		Bool("hostname_auto", nodeCfg.HostnameAuto).
		Bool("reimage_pending", nodeCfg.ReimagePending).
		Bool("dry_run", dryRun).
		Str("action", action).Msg("node registered")

	// Pre-merge group extra mounts so the deploy client's ExtraMounts is complete.
	nodeCfg = mergeGroupExtraMounts(r.Context(), h.DB, nodeCfg)

	writeJSON(w, http.StatusOK, api.RegisterResponse{
		NodeConfig: &nodeCfg,
		Action:     action,
		DryRun:     dryRun,
	})
}

// DeployComplete handles POST /api/v1/nodes/:id/deploy-complete.
// Called by the clonr CLI after a successful deployment finalize.
// Sets last_deploy_succeeded_at and clears reimage_pending, transitioning the
// node to NodeStateDeployed. Subsequent PXE boots will return "exit" (disk boot).
// Also transitions any active reimage record to succeeded.
func (h *NodesHandler) DeployComplete(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	// Confirm node exists before updating.
	if _, err := h.DB.GetNodeConfig(r.Context(), id); err != nil {
		writeError(w, err)
		return
	}

	if err := h.DB.RecordDeploySucceeded(r.Context(), id); err != nil {
		log.Error().Err(err).Str("node_id", id).Msg("deploy-complete: record succeeded")
		writeError(w, err)
		return
	}

	// Transition the active reimage record (if any) to complete.
	active, err := h.DB.GetActiveReimageForNode(r.Context(), id)
	if err != nil {
		log.Warn().Err(err).Str("node_id", id).Msg("deploy-complete: could not look up active reimage (non-fatal)")
	} else if active != nil {
		if dbErr := h.DB.UpdateReimageRequestStatus(r.Context(), active.ID, api.ReimageStatusComplete, ""); dbErr != nil {
			log.Warn().Err(dbErr).Str("reimage_id", active.ID).Msg("deploy-complete: could not update reimage record (non-fatal)")
		} else {
			log.Info().Str("reimage_id", active.ID).Str("node_id", id).Msg("deploy-complete: reimage record transitioned to complete")
		}
	}

	log.Info().Str("node_id", id).Msg("deploy-complete: node marked deployed")
	w.WriteHeader(http.StatusNoContent)
}

// DeployFailed handles POST /api/v1/nodes/:id/deploy-failed.
// Called by the clonr CLI after a deployment failure.
// Sets last_deploy_failed_at, transitioning the node to NodeStateFailed.
// Does not clear reimage_pending -- admin decides whether to retry or cancel.
// Accepts an optional DeployFailedPayload body to capture exit code / phase detail.
func (h *NodesHandler) DeployFailed(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	// Parse optional structured payload — tolerate missing/empty body.
	var payload api.DeployFailedPayload
	if r.ContentLength != 0 {
		if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
			log.Warn().Err(err).Str("node_id", id).Msg("deploy-failed: could not parse payload (ignored)")
		}
	}

	// Confirm node exists before updating.
	if _, err := h.DB.GetNodeConfig(r.Context(), id); err != nil {
		writeError(w, err)
		return
	}

	if err := h.DB.RecordDeployFailed(r.Context(), id); err != nil {
		log.Error().Err(err).Str("node_id", id).Msg("deploy-failed: record failed")
		writeError(w, err)
		return
	}

	// Transition the active reimage record (if any) to failed with exit detail.
	active, err := h.DB.GetActiveReimageForNode(r.Context(), id)
	if err != nil {
		log.Warn().Err(err).Str("node_id", id).Msg("deploy-failed: could not look up active reimage (non-fatal)")
	} else if active != nil {
		msg := payload.Message
		if msg == "" {
			msg = "deploy agent reported failure"
		}
		if dbErr := h.DB.UpdateReimageRequestFailed(r.Context(), active.ID, msg, payload.ExitCode, payload.ExitName, payload.Phase); dbErr != nil {
			log.Warn().Err(dbErr).Str("reimage_id", active.ID).Msg("deploy-failed: could not update reimage record (non-fatal)")
		} else {
			log.Info().
				Str("reimage_id", active.ID).
				Str("node_id", id).
				Int("exit_code", payload.ExitCode).
				Str("exit_name", payload.ExitName).
				Str("phase", payload.Phase).
				Msg("deploy-failed: reimage record transitioned to failed")
		}
	}

	log.Warn().
		Str("node_id", id).
		Int("exit_code", payload.ExitCode).
		Str("exit_name", payload.ExitName).
		Str("phase", payload.Phase).
		Msg("deploy-failed: node marked failed")
	w.WriteHeader(http.StatusNoContent)
}

// VerifyBoot handles POST /api/v1/nodes/:id/verify-boot. ADR-0008.
//
// Called by the deployed OS on first boot (via clonr-verify-boot.service systemd
// oneshot). Proves the bootloader, kernel, and systemd all started successfully.
//
// Auth: node-scoped token only. The token's bound node_id must match the URL {id}.
// Admin-scoped keys are NOT accepted here — enforced by requireNodeOwnership
// middleware in the router registration. This ensures only the node itself can
// report its own boot (the token written to /etc/clonr/node-token at finalize time
// is node-scoped and bound to that specific node's ID).
//
// State transitions:
//   deploy_completed_preboot_at set, deploy_verified_booted_at NULL
//   → deploy_verified_booted_at = now()  (first call)
//   → deploy_verified_booted_at unchanged (subsequent calls; only last_seen_at updates)
//
// Returns 204 No Content on success.
func (h *NodesHandler) VerifyBoot(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	// Parse the phone-home payload. Tolerate a missing body gracefully.
	var payload api.VerifyBootRequest
	if r.ContentLength != 0 {
		if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
			log.Warn().Err(err).Str("node_id", id).Msg("verify-boot: could not parse payload (ignored)")
		}
	}

	// Confirm node exists before updating.
	if _, err := h.DB.GetNodeConfig(r.Context(), id); err != nil {
		writeError(w, err)
		return
	}

	if err := h.DB.RecordVerifyBooted(r.Context(), id); err != nil {
		log.Error().Err(err).Str("node_id", id).Msg("verify-boot: db update failed")
		writeError(w, err)
		return
	}

	log.Info().
		Str("node_id", id).
		Str("hostname", payload.Hostname).
		Str("kernel_version", payload.KernelVersion).
		Str("systemctl_state", payload.SystemctlState).
		Str("os_release", payload.OSRelease).
		Float64("uptime_seconds", payload.UptimeSeconds).
		Msgf("verify-boot: node %s (%s) verified booted: kernel=%s, systemctl=%s",
			id, payload.Hostname, payload.KernelVersion, payload.SystemctlState)

	w.WriteHeader(http.StatusNoContent)
}

// extractNodeIdentity parses the hardware profile JSON to find the primary MAC
// and hostname. Returns empty strings on any parse failure.
func extractNodeIdentity(profile []byte) (mac, hostname string) {
	var hw struct {
		Hostname string `json:"Hostname"`
		NICs     []struct {
			Name  string `json:"Name"`
			MAC   string `json:"MAC"`
			State string `json:"State"`
		} `json:"NICs"`
	}
	if err := json.Unmarshal(profile, &hw); err != nil {
		return "", ""
	}

	hostname = hw.Hostname

	// Pick first non-loopback NIC with a real MAC.
	for _, nic := range hw.NICs {
		if nic.Name == "lo" || nic.MAC == "" || nic.MAC == "00:00:00:00:00:00" {
			continue
		}
		return nic.MAC, hostname
	}
	return "", hostname
}
